# Generated by Django 4.1.1 on 2022-12-13 12:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('seirv_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Dengue',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('N_h', models.FloatField()),
                ('N_v', models.FloatField()),
                ('t_duration', models.FloatField()),
                ('bite_n', models.FloatField()),
                ('bv_input', models.FloatField()),
                ('bh_input', models.FloatField()),
                ('uv_input', models.FloatField()),
                ('h_recov_input', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='InfectiousDisease',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('N_in', models.FloatField()),
                ('t_duration', models.FloatField()),
                ('R0_input', models.FloatField()),
                ('t_incubation', models.FloatField()),
                ('t_infection', models.FloatField()),
                ('E_in', models.FloatField()),
                ('I_in', models.FloatField()),
                ('R_in', models.FloatField()),
                ('v_eff', models.FloatField()),
                ('mask_use', models.BooleanField()),
            ],
        ),
        migrations.AlterField(
            model_name='customuser',
            name='profession',
            field=models.CharField(choices=[('Student', 'Student'), ('Doctor', 'Doctor')], default='Student', max_length=100),
        ),
    ]
