# Generated by Django 4.1.1 on 2022-12-14 02:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('seirv_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='profession',
            field=models.CharField(choices=[('Student', 'Student'), ('Hospital Staff', 'Hospital Staff')], default='Student', max_length=100),
        ),
    ]
