# Generated by Django 4.1.1 on 2022-12-13 06:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('seirv_app', '0002_alter_customuser_profession'),
    ]

    operations = [
        migrations.CreateModel(
            name='InfectiousDisease',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('N_in', models.DecimalField(decimal_places=4, max_digits=8)),
                ('t_duration', models.DecimalField(decimal_places=4, max_digits=8)),
                ('R0_input', models.DecimalField(decimal_places=4, max_digits=8)),
                ('t_incubation', models.DecimalField(decimal_places=4, max_digits=8)),
                ('t_infection', models.DecimalField(decimal_places=4, max_digits=8)),
            ],
        ),
    ]
