# Generated by Django 4.1.1 on 2022-12-13 07:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('seirv_app', '0003_infectiousdisease'),
    ]

    operations = [
        migrations.AlterField(
            model_name='infectiousdisease',
            name='N_in',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='infectiousdisease',
            name='R0_input',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='infectiousdisease',
            name='t_duration',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='infectiousdisease',
            name='t_incubation',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='infectiousdisease',
            name='t_infection',
            field=models.FloatField(),
        ),
    ]
